@extends('layouts.app')

@section('title', 'Profile')

@section('content')

<div class="container-xl">
    <div class="mb-3">
        <ul class="nav nav-pills sticky-top">
          <li class="nav-item">
            <a class="nav-link" href="/profile">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/security">Security</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/settings">Settings</a>
          </li>
        </ul>
    </div>

    <div class="card">
        <div class="card-header">
            <i class="fa fa-lock"></i>Recent Logins
        </div>

        <table class="table table-borderless table-striped">
            @foreach ($recentLogins as $login)
            <tr>
                <td>{{ $login->logged_at }}</td>
                <td>{{ $login->ip_address }}</td>
                <td>{{ $login->user_agent }}</td>
            </tr>
            @endforeach
        </table>
    </div>
    <div class="card">
        <div class="card-header">
            <i class="fa fa-lock"></i>Two-factor Authentication 
        </div>

        <div class="card-body">
            <div class="alert alert-danger" role="alert">
                Currently not implemented
            </div>
            <div class="alert alert-info" role="alert">
                <p>For additional account security, you can enable two factor authentication.</p>
                <p>When you enabled this feature, you need to enter a code generated by your authentication app in additional to your credentials while login.</p>
            </div>
            <div class="row">
                <div class="col-auto">
                    <qrcode value="{{ $uri }}" :options="{ width: 200 }"></qrcode>
                </div>
                <div class="col-md">
                    <div class="form-group">
                        <label>Key</label>
                        <input value="{{ $secret }}" class="form-control"/>
                    </div>
                    <div class="form-group">
                        <label>To confirm, enter the 6-digit code from app</label>
                        <input class="form-control" />
                    </div>
                </div>
            </div>
        </div>
                    
        <div class="card-footer">
            <button type="submit" class="btn btn-primary" :disabled="submiting">
                <i class="fa" :class="submiting ? 'fa-spinner' : 'fa-check'"></i>
                    {{ trans('brackets/admin-ui::admin.btn.save') }}
            </button>
        </div>
    </div>
</div>

@endsection
