<?php

namespace App\Models;

use App\Exceptions\AlreadyProcessedException;
use App\Exceptions\InactiveActivityException;
use App\Exceptions\NotAdmittedException;
use App\Exceptions\NotCheckedInException;
use App\Exceptions\NoVacancyException;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Relations\MorphPivot;
use Illuminate\Support\InteractsWithTime;
use Ramsey\Uuid\Uuid;

class Participation extends MorphPivot
{

    use InteractsWithTime;
    /**
     * @var string table for this model
     */
    protected $table = 'participations';

    /**
     * @var string[] attributes appended
     */
    protected $appends = ['participation_status', 'attend_status'];

    /**
     * @var string[] columns need to be cast
     */
    protected $casts = [
        'approved_at' => 'datetime',
        'rejected_at' => 'datetime',
        'cancelled_at' => 'datetime',
        'arrived_at' => 'datetime',
        'left_at' => 'datetime',
    ];

    public $incrementing = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->{$model->getKeyName()}  = Uuid::uuid4()->toString();
        });
    }

    public function otp()
    {
        $parameters = [
            'id' => $this->id,
            'expires' => $this->availableAt(Carbon::now()->addSeconds(10))
        ];

        return serialize($parameters + [ 'signature' => hash_hmac('sha256', serialize($parameters), getenv('APP_KEY'))]);
    }

    public function participant()
    {
        return $this->belongsTo(User::class);
    }

    public function activity()
    {
        return $this->belongsTo(Activity::class);
    }

    /**
     * Participation Status
     *
     * @return string
     */
    public function getParticipationStatusAttribute(): string
    {
        if ($this->cancelled_at) {
            return 'cancelled';
        }

        if ($this->rejected_at) {
            return 'rejected';
        }

        if ($this->approved_at) {
            return 'admitted';
        }

        return 'pending';
    }

    /**
     * Attend status
     *
     * @return string
     */
    public function getAttendStatusAttribute(): string
    {
        if ($this->left_at) {
            return 'left';
        }

        if ($this->arrived_at) {
           return 'attended';
        } else {
            return 'unattended';
        }
    }

    /**
     * Reject the participation request
     *
     * @throws AlreadyProcessedException
     */
    public function reject()
    {
        $this->approved_at = null;
        $this->rejected_at = Carbon::now();
        $this->save();
    }

    /**
     * Approve participation request
     *
     * @throws AlreadyProcessedException
     * @throws NoVacancyException
     */
    public function admit()
    {
        if (!($this->activity->quota == 0) &&
            !($this->activity->quota > $this->activity->getAdmittedApplicantCount())) {
            throw new NoVacancyException();
        }

        $this->approved_at = Carbon::now();
        $this->rejected_at = null;
        $this->save();
    }

    /**
     * Check in participant
     *
     * @throws NotAdmittedException
     * @throws InactiveActivityException
     * @throws AlreadyProcessedException
     */
    public function checkIn()
    {
        $this->beforeCheckIn();
        $this->arrived_at = Carbon::now();
        $this->save();
    }


    /**
     * Check out participant
     *
     * @throws InactiveActivityException
     * @throws NotAdmittedException
     * @throws NotCheckedInException
     */
    public function checkOut()
    {
        if ($this->getParticipationStatusAttribute() != 'admitted') {
            throw new NotAdmittedException();
        }

        if ($this->getAttendStatusAttribute() != 'attended') {
            throw new NotCheckedInException();
        }

        $this->left_at = Carbon::now();
        $this->save();
    }

    /**
     * @throws InactiveActivityException
     */
    private function checkActivityStatus()
    {
        if (!isset($this->pivotParent)) {
            $this->pivotParent = $this->activity;
        }

        if ($this->pivotParent->getStatus() != 'ongoing') {
            throw new InactiveActivityException();
        }
    }

    /**
     * Check conditions before check in
     *
     * @throws NotAdmittedException
     * @throws InactiveActivityException
     */
    private function beforeCheckIn()
    {
        $this->checkActivityStatus();

        if ($this->getParticipationStatusAttribute() != 'admitted') {
            throw new NotAdmittedException();
        }
    }
}
