<?php

namespace Tests\Unit;

use App\Exceptions\AlreadyProcessedException;
use App\Exceptions\InactiveActivityException;
use App\Exceptions\NotAdmittedException;
use App\Exceptions\NotCheckedInException;
use App\Models\Activity;
use App\Models\Participation;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\Concerns\InteractsWithDatabase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ParticipationTest extends TestCase
{
    use InteractsWithDatabase;
    use RefreshDatabase;

    /**
     * @var Participation
     */
    private Participation $participation;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $activity = factory(Activity::class)->create([
            'starts_at' => Carbon::now()->subDay(),
            'ends_at' => Carbon::now()->addDay(),
            'is_published' => true
        ]);

        $participant = factory(User::class)->create();

        $activity->addParticipant($participant);
        $this->participation = $activity->participations($participant);
    }

    public function testPivotParentIsInstanceOfActivity(): void
    {
        $this->assertInstanceOf(Activity::class, $this->participation->pivotParent);
    }

    public function testApproveParticipant(): void
    {
        $this->participation->admit();
        $this->assertNotNull($this->participation->approved_at);
    }

    public function testRejectParticipant(): void
    {
        $this->participation->reject();
        $this->assertNotNull($this->participation->rejected_at);
    }

    public function testDuplicateApprove(): void
    {
        $this->expectException(AlreadyProcessedException::class);
        $this->participation->admit();
        $this->participation->admit();
    }

    public function testCheckIn(): void
    {
        $this->participation->admit();
        $this->participation->checkIn();
        $this->assertNotNull($this->participation->arrived_at);
    }

    public function testCheckInNotAdmitted(): void
    {
        $this->expectException(NotAdmittedException::class);
        $this->participation->checkIn();
    }

    public function testCheckInOnActivityNotStarted(): void
    {
        $this->expectException(InactiveActivityException::class);
        $this->participation->pivotParent->starts_at = Carbon::now()->addMinutes(30);
        $this->participation->admit();
        $this->participation->checkIn();
    }

    public function testCheckOut(): void
    {
        $this->participation->admit();
        $this->participation->checkIn();
        $this->participation->checkOut();

        $this->assertNotNull($this->participation->left_at);
    }

    public function testCheckOutButNotCheckedIn(): void
    {
        $this->expectException(NotCheckedInException::class);
        $this->participation->admit();
        $this->participation->checkOut();
    }
}
